services:
  - type: web
    name: flask-ml-app
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    runtime: python 3.10
