services:
  - type: web
    name: flask-ml-app
    env: python
    plan: free
    buildCommand: pip install --no-build-isolation --no-cache-dir -r requirements.txt
    startCommand: python app.py
    runtime: python 3.10
